### ISSUE TITLE
iOS errors

### ISSUE THREAD

**Issue by MjG345** [fkie-cad/friTap#3]
Hi,

I've found two issues when trying to extract keys of iOS apps. I've used iOS 14 devices for all my tests.

- friTap 1.0.6 not able to properly hook on iOS, however friTap 1.0.3 works fine:

![ios_key_dump_error](https://user-images.githubusercontent.com/115788683/195822750-ffef5aab-1f15-4400-b943-bf94cb238492.png)

![ios_key_dump_error_2](https://user-images.githubusercontent.com/115788683/195822788-7b1c75ce-0f6a-4b49-a9af-95e9f3a2beed.png)

![ios_key_dump_ok](https://user-images.githubusercontent.com/115788683/195822806-a2692a50-bc28-4121-9eb0-5fbc00f0ebdb.png)

- friTap (any version) freezes when spawning an app -- at least on all my test under iOS 14:

![spawn_error_ios](https://user-images.githubusercontent.com/115788683/195823524-955c7fea-4337-4d12-8460-805dd36cc64e.png)

It seems that the tls_lib is not yet loaded when Frida tries to hook it. A simple workaround could be a while loop:

<img width="490" alt="lib_load" src="https://user-images.githubusercontent.com/115788683/195823877-a1e1a91e-ba84-4c43-a0da-df00d01f2678.png">

Thanks!

**Comment by monkeywave** [comment]
Hi,

thx for your issue. We will have a look into this :-)

**Comment by monkeywave** [comment]
Should be fixed in the latest version (1.0.7)

**Comment by MjG345** [comment]
Hi,

Error has changed. Still not working properly:

![error1](https://user-images.githubusercontent.com/115788683/197170282-2cd6aa3e-41ed-4b37-bf4b-2624f450baaa.png)

![error2](https://user-images.githubusercontent.com/115788683/197170315-a8870449-80a4-47f2-ac57-589317a25b15.png)

Thanks!

**Comment by monkeywave** [comment]
Thx for reporting this :-) - this should now be fixed (version >= 1.0.7.1) - at least this new bug :-)
